var https = require('https');

var CONFIG = {
  refreshToken: process.env.REFRESH_TOKEN,
    cognitoClientId: '2ek0ok90bl4oiu1i5qno54286a',
      cognitoRegion:   'eu-central-1',
        calendarId:      '69a5839576697dce41cbf7c7',
          graphqlEndpoint: 'https://9mtze3hb29.execute-api.eu-central-1.amazonaws.com/graphql',
          };

          function httpPost(url, headers, body) {
            return new Promise(function(resolve, reject) {
                var parsed  = new URL(url);
                    var data    = JSON.stringify(body);
                        var allHeaders = Object.assign({}, headers, { 'Content-Length': Buffer.byteLength(data) });
                            var req = https.request(
                                  { hostname: parsed.hostname, path: parsed.pathname, method: 'POST', headers: allHeaders },
                                        function(res) {
                                                var raw = '';
                                                        res.on('data', function(chunk) { raw += chunk; });
                                                                res.on('end', function() {
                                                                          try { resolve(JSON.parse(raw)); } catch(e) { resolve(raw); }
                                                                                  });
                                                                                        }
                                                                                            );
                                                                                                req.on('error', reject);
                                                                                                    req.write(data);
                                                                                                        req.end();
                                                                                                          });
                                                                                                          }
                                                                                                          
                                                                                                          function refreshIdToken() {
                                                                                                            console.log('[1/4] Refrescando token...');
                                                                                                              return httpPost(
                                                                                                                  'https://cognito-idp.' + CONFIG.cognitoRegion + '.amazonaws.com/',
                                                                                                                      { 'Content-Type': 'application/x-amz-json-1.1', 'X-Amz-Target': 'AWSCognitoIdentityProviderService.InitiateAuth' },
                                                                                                                          { AuthFlow: 'REFRESH_TOKEN_AUTH', ClientId: CONFIG.cognitoClientId, AuthParameters: { REFRESH_TOKEN: CONFIG.refreshToken } }
                                                                                                                            ).then(function(result) {
                                                                                                                                var token = result.AuthenticationResult && result.AuthenticationResult.IdToken;
                                                                                                                                    if (!token) throw new Error('Fallo al refrescar token: ' + JSON.stringify(result));
                                                                                                                                        console.log('    OK Token refrescado');
                                                                                                                                            return token;
                                                                                                                                              });
                                                                                                                                              }
                                                                                                                                              
                                                                                                                                              function esDiaFestivo(token, hoy) {
                                                                                                                                                var mes = hoy.getMonth();
                                                                                                                                                  var dia = hoy.getDate();
                                                                                                                                                    var anio = hoy.getFullYear();
                                                                                                                                                      console.log('[2/4] Comprobando festivos...');
                                                                                                                                                        var QUERY = 'query MyCalendars { myCalendars { _id year months { month days { day isFestive } } } }';
                                                                                                                                                          return httpPost(
                                                                                                                                                              CONFIG.graphqlEndpoint,
                                                                                                                                                                  { 'accept': '*/*', 'content-type': 'application/json', 'token': token },
                                                                                                                                                                      { operationName: 'MyCalendars', variables: {}, query: QUERY }
                                                                                                                                                                        ).then(function(result) {
                                                                                                                                                                            if (result.errors) throw new Error('Error GraphQL calendarios: ' + JSON.stringify(result.errors));
                                                                                                                                                                                var calendars = result.data && result.data.myCalendars;
                                                                                                                                                                                    if (!calendars || calendars.length === 0) { console.log('    Aviso: sin calendario'); return false; }
                                                                                                                                                                                        var cal = calendars.find(function(c) { return c.year === anio; }) || calendars[0];
                                                                                                                                                                                            var mesData = cal.months && cal.months.find(function(m) { return m.month === mes; });
                                                                                                                                                                                                if (!mesData) { console.log('    Aviso: mes no encontrado'); return false; }
                                                                                                                                                                                                    var diaData = mesData.days && mesData.days.find(function(d) { return d.day === dia; });
                                                                                                                                                                                                        var festivo = diaData ? diaData.isFestive : false;
                                                                                                                                                                                                            if (festivo) console.log('    Hoy es festivo — no se ficha');
                                                                                                                                                                                                                else console.log('    OK No es festivo');
                                                                                                                                                                                                                    return festivo;
                                                                                                                                                                                                                      });
                                                                                                                                                                                                                      }
                                                                                                                                                                                                                      
                                                                                                                                                                                                                      function esDiaVacaciones(token, hoy) {
                                                                                                                                                                                                                        var mes  = hoy.getMonth();
                                                                                                                                                                                                                          var dia  = hoy.getDate();
                                                                                                                                                                                                                            var anio = hoy.getFullYear();
                                                                                                                                                                                                                              console.log('[3/4] Comprobando vacaciones...');
                                                                                                                                                                                                                                var QUERY = 'query MyVacationDays($calendarId: String!, $month: Int!, $year: Int!) { myVacationDays(calendarId: $calendarId, month: $month, year: $year) { _id day month year accountId __typename } }';
                                                                                                                                                                                                                                  return httpPost(
                                                                                                                                                                                                                                      CONFIG.graphqlEndpoint,
                                                                                                                                                                                                                                          { 'accept': '*/*', 'content-type': 'application/json', 'token': token },
                                                                                                                                                                                                                                              { operationName: 'MyVacationDays', variables: { calendarId: CONFIG.calendarId, month: mes, year: anio }, query: QUERY }
                                                                                                                                                                                                                                                ).then(function(result) {
                                                                                                                                                                                                                                                    if (result.errors) throw new Error('Error GraphQL vacaciones: ' + JSON.stringify(result.errors));
                                                                                                                                                                                                                                                        var dias = result.data && result.data.myVacationDays;
                                                                                                                                                                                                                                                            if (!dias || dias.length === 0) { console.log('    OK Sin vacaciones este mes'); return false; }
                                                                                                                                                                                                                                                                var esVacaciones = dias.some(function(d) { return d.day === dia; });
                                                                                                                                                                                                                                                                    if (esVacaciones) console.log('    Hoy es vacaciones — no se ficha');
                                                                                                                                                                                                                                                                        else console.log('    OK No es dia de vacaciones');
                                                                                                                                                                                                                                                                            return esVacaciones;
                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                              function clockToggle(token) {
                                                                                                                                                                                                                                                                                var SEGMENT_FIELDS = [
                                                                                                                                                                                                                                                                                    'fragment SegmentFields on SegmentType {',
                                                                                                                                                                                                                                                                                        '  _id accountId assignedManagerId organizationId',
                                                                                                                                                                                                                                                                                            '  chipClockIn  { chipId chipAlias organizationId __typename }',
                                                                                                                                                                                                                                                                                                '  chipClockOut { chipId chipAlias organizationId __typename }',
                                                                                                                                                                                                                                                                                                    '  coordinatesClockIn  { lat lon __typename }',
                                                                                                                                                                                                                                                                                                        '  coordinatesClockOut { lat lon __typename }',
                                                                                                                                                                                                                                                                                                            '  start startAt end endAt newStart newEnd newStartAt newEndAt',
                                                                                                                                                                                                                                                                                                                '  finalStart finalEnd finalStartAt finalEndAt',
                                                                                                                                                                                                                                                                                                                    '  issues { _id createdById handledById segmentId start startAt end endAt message status __typename }',
                                                                                                                                                                                                                                                                                                                        '  status offlineEntryId __typename',
                                                                                                                                                                                                                                                                                                                            '}'
                                                                                                                                                                                                                                                                                                                              ].join('\n');
                                                                                                                                                                                                                                                                                                                                var MUTATION = [
                                                                                                                                                                                                                                                                                                                                    SEGMENT_FIELDS,
                                                                                                                                                                                                                                                                                                                                        'mutation ClockToggle($chip: ChipInputType $clockBySchedule: Boolean $coordinates: CoordinatesInputType $recordedAt: Float $offlineEntryId: String) {',
                                                                                                                                                                                                                                                                                                                                            '  clockToggle(chip: $chip clockBySchedule: $clockBySchedule coordinates: $coordinates recordedAt: $recordedAt offlineEntryId: $offlineEntryId) {',
                                                                                                                                                                                                                                                                                                                                                '    ...SegmentFields',
                                                                                                                                                                                                                                                                                                                                                    '  }',
                                                                                                                                                                                                                                                                                                                                                        '}'
                                                                                                                                                                                                                                                                                                                                                          ].join('\n');
                                                                                                                                                                                                                                                                                                                                                            console.log('[4/4] Enviando fichaje...');
                                                                                                                                                                                                                                                                                                                                                              return httpPost(
                                                                                                                                                                                                                                                                                                                                                                  CONFIG.graphqlEndpoint,
                                                                                                                                                                                                                                                                                                                                                                      { 'accept': '*/*', 'content-type': 'application/json', 'token': token },
                                                                                                                                                                                                                                                                                                                                                                          { operationName: 'ClockToggle', variables: { recordedAt: Date.now() }, query: MUTATION }
                                                                                                                                                                                                                                                                                                                                                                            ).then(function(result) {
                                                                                                                                                                                                                                                                                                                                                                                if (result.errors) throw new Error('Error GraphQL fichaje: ' + JSON.stringify(result.errors));
                                                                                                                                                                                                                                                                                                                                                                                    return result.data && result.data.clockToggle;
                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                      function main() {
                                                                                                                                                                                                                                                                                                                                                                                        var hoy     = new Date();
                                                                                                                                                                                                                                                                                                                                                                                          var weekday = hoy.getDay();
                                                                                                                                                                                                                                                                                                                                                                                            console.log('\n=== Ficha.Work Auto-Fichaje ===');
                                                                                                                                                                                                                                                                                                                                                                                              console.log('Fecha: ' + hoy.toISOString());
                                                                                                                                                                                                                                                                                                                                                                                                if (weekday === 0 || weekday === 6) { console.log('Fin de semana — no se ficha.'); return; }
                                                                                                                                                                                                                                                                                                                                                                                                  var idToken;
                                                                                                                                                                                                                                                                                                                                                                                                    refreshIdToken()
                                                                                                                                                                                                                                                                                                                                                                                                        .then(function(token) { idToken = token; return esDiaFestivo(token, hoy); })
                                                                                                                                                                                                                                                                                                                                                                                                            .then(function(festivo) { if (festivo) return true; return esDiaVacaciones(idToken, hoy); })
                                                                                                                                                                                                                                                                                                                                                                                                                .then(function(saltar) {
                                                                                                                                                                                                                                                                                                                                                                                                                      if (saltar) { console.log('\nSaltando fichaje.'); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                            return clockToggle(idToken).then(function(segment) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    var estado = (segment && segment.status === 'open') ? 'ENTRADA fichada' : 'SALIDA fichada';
                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('\nOK ' + estado + ' correctamente');
                                                                                                                                                                                                                                                                                                                                                                                                                                                    console.log('   ID: ' + (segment && segment._id));
                                                                                                                                                                                                                                                                                                                                                                                                                                                            console.log('   Estado: ' + (segment && segment.status));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          .catch(function(err) { console.error('\nError: ' + err.message); process.exit(1); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          main();
